---
title: "Intro Description"
author: "Alex Wong"
date: "December 4, 2017"
output: html_document
---

# Introduction

## The Data
This app deals with a data set that talks about people sleeping alone vs. sleeping with a spouse or significant other. The dataset is called [sleeping-alone-data.csv](https://sleeping.data.csv) and was found on the GitHub of FiveThirtyEight which was added by the user anderewflowers. This dataset contains information on individuals who report sleeping alone. This information includes their martial status, how long they have been with their partner, what age range they fall into, and much more.

## Questions
Some questions we asked about this data was :

* What are some of the reasons partners end up sleeping separately?
* Does sleeping with your spouse/significant other deepen your relationship?
* What kind of person is most susceptible to sleeping alone?

## Target Audience
This data pertains mostly to people who are either in a relationship, or are starting a new relationship. The information deals with couples, and other couples can learn the effects or trends that sleeping together or alone has whether they be positive, negative, or not really have a strong effect on most people.
